#!/usr/bin/env instantfpc

{$mode delphi}
{$H+}

uses
  Classes,
  Process,
  SysUtils,

  FileUtils in 'source/shared/FileUtils.pas';

type
  TBuildMode = (bmDev, bmProd);

var
  I: Integer;
  BuildTriggers: TStringList;
  BuildMode: TBuildMode = bmDev;
  GVersion, GCommit, GBuildDate: string;

function ComputeVersion: string;
var
  Describe: string;
  DashPos: SizeInt;
begin
  if not RunCommand('git', ['describe', '--tags', '--always'], Describe) then
    Describe := '';
  Describe := Trim(Describe);

  if (Describe = '') or (Pos('.', Describe) = 0) then
    Result := '0.0.0-dev'
  else
  begin
    DashPos := Pos('-', Describe);
    if DashPos > 0 then
      Result := Copy(Describe, 1, DashPos - 1) + '-dev'
    else
      Result := Describe;
  end;
end;

function ComputeCommit: string;
begin
  if not RunCommand('git', ['rev-parse', '--short', 'HEAD'], Result) then
    Result := '';
  Result := Trim(Result);
  if Result = '' then
    Result := 'unknown';
end;

function ComputeBuildDate: string;
begin
  Result := FormatDateTime('yyyy-mm-dd', Now);
end;

procedure GenerateVersionInclude(const AVersion, ACommit, ABuildDate: string);
var
  F: TextFile;
begin
  AssignFile(F, 'source' + DirectorySeparator + 'units' + DirectorySeparator + 'Goccia.Version.Generated.inc');
  Rewrite(F);
  try
    WriteLn(F, '// Auto-generated by build.pas — do not edit');
    WriteLn(F, 'const');
    WriteLn(F, '  BAKED_VERSION = ''', AVersion, ''';');
    WriteLn(F, '  BAKED_COMMIT = ''', ACommit, ''';');
    WriteLn(F, '  BAKED_BUILD_DATE = ''', ABuildDate, ''';');
  finally
    CloseFile(F);
  end;
end;

procedure PrintVersion(const AVersion, ACommit, ABuildDate: string);
begin
  WriteLn('Version: ', AVersion, ' (', ACommit, ') built ', ABuildDate);
  WriteLn('');
end;

procedure StripBlockComments(var AText: string; var AInBlock: Boolean);
var
  OpenPos, ClosePos: SizeInt;
  Sub: string;
begin
  repeat
    if AInBlock then
    begin
      ClosePos := Pos('}', AText);
      if ClosePos = 0 then
        ClosePos := Pos('*)', AText);
      if ClosePos > 0 then
      begin
        if AText[ClosePos] = '*' then
          Delete(AText, 1, ClosePos + 1)
        else
          Delete(AText, 1, ClosePos);
        AText := Trim(AText);
        AInBlock := False;
      end
      else
      begin
        AText := '';
        Exit;
      end;
    end
    else
    begin
      OpenPos := Pos('{', AText);
      if (OpenPos > 0) and (Copy(AText, OpenPos, 2) <> '{$') then
      begin
        Sub := Copy(AText, OpenPos + 1, Length(AText));
        ClosePos := Pos('}', Sub);
        if ClosePos > 0 then
        begin
          Delete(AText, OpenPos, ClosePos + 1);
          AText := Trim(AText);
        end
        else
        begin
          Delete(AText, OpenPos, Length(AText));
          AText := Trim(AText);
          AInBlock := True;
          Exit;
        end;
        Continue;
      end;

      OpenPos := Pos('(*', AText);
      if OpenPos > 0 then
      begin
        Sub := Copy(AText, OpenPos + 2, Length(AText));
        ClosePos := Pos('*)', Sub);
        if ClosePos > 0 then
        begin
          Delete(AText, OpenPos, ClosePos + 3);
          AText := Trim(AText);
        end
        else
        begin
          Delete(AText, OpenPos, Length(AText));
          AText := Trim(AText);
          AInBlock := True;
          Exit;
        end;
        Continue;
      end;

      Exit;
    end;
  until AText = '';
end;

procedure CountLines(const AFileName: string; out ALOC, ASLOC: Integer);
var
  F: TextFile;
  Line, Trimmed: string;
  InBlock: Boolean;
begin
  ALOC := 0;
  ASLOC := 0;
  InBlock := False;

  AssignFile(F, AFileName);
  Reset(F);
  try
    while not EOF(F) do
    begin
      ReadLn(F, Line);
      Inc(ALOC);
      Trimmed := Trim(Line);

      StripBlockComments(Trimmed, InBlock);

      if Trimmed = '' then
        Continue;
      if Copy(Trimmed, 1, 2) = '//' then
        Continue;

      Inc(ASLOC);
    end;
  finally
    CloseFile(F);
  end;
end;

function FormatNumber(const AValue: Integer): string;
var
  S: string;
  Len, InsertPos: Integer;
begin
  S := IntToStr(AValue);
  Len := Length(S);
  InsertPos := Len - 3;
  while InsertPos > 0 do
  begin
    Insert(',', S, InsertPos + 1);
    Dec(InsertPos, 3);
  end;
  Result := S;
end;

procedure PrintSourceStats;
var
  Files: TStringList;
  K, FileLOC, FileSLOC, TotalLOC, TotalSLOC: Integer;
begin
  TotalLOC := 0;
  TotalSLOC := 0;

  Files := TStringList.Create;
  try
    Files.AddStrings(FindAllFiles('source/units', '.pas'));
    Files.AddStrings(FindAllFiles('source/shared', '.pas'));
    Files.AddStrings(FindAllFiles('source/app', '.pas'));
    Files.AddStrings(FindAllFiles('source/app', '.dpr'));
    Files.AddStrings(FindAllFiles('source/units', '.inc'));

    for K := 0 to Files.Count - 1 do
    begin
      CountLines(Files[K], FileLOC, FileSLOC);
      TotalLOC := TotalLOC + FileLOC;
      TotalSLOC := TotalSLOC + FileSLOC;
    end;

    WriteLn('Source: ', FormatNumber(TotalLOC), ' LOC | ', FormatNumber(TotalSLOC), ' SLOC (', Files.Count, ' files)');
    WriteLn('');
  finally
    Files.Free;
  end;
end;

function FPCArgs(const ASource: string): TStringArray;
var
  Arch: string;
  Args: TStringList;
  J: Integer;
begin
  Args := TStringList.Create;
  try
    Arch := GetEnvironmentVariable('FPC_TARGET_CPU');
    if Arch <> '' then
      Args.Add('-P' + Arch);

    Args.Add('@config.cfg');

    if BuildMode = bmProd then
    begin
      Args.Add('-O4');
      Args.Add('-dPRODUCTION');
      Args.Add('-Xs');
      Args.Add('-CX');
      Args.Add('-XX');
      Args.Add('-B');
    end else
    begin
      Args.Add('-O-');
      Args.Add('-gw');
      Args.Add('-godwarfsets');
      Args.Add('-gl');
      Args.Add('-Ct');
      Args.Add('-Cr');
      Args.Add('-Sa');
    end;

    Args.Add('-vw-n-h-i-l-d-u-t-p-c-x-');
    Args.Add(ASource);

    SetLength(Result, Args.Count);
    for J := 0 to Args.Count - 1 do
      Result[J] := Args[J];
  finally
    Args.Free;
  end;
end;

procedure BuildREPL;
var
  Output: string;
begin
  WriteLn('Building GocciaREPL...');
  if not RunCommand('fpc', FPCArgs('source/app/GocciaREPL.dpr'), Output) then
  begin
    WriteLn(Output);
    WriteLn('GocciaREPL build failed');
    Halt(1);
  end;
  WriteLn(Output);
  WriteLn('GocciaREPL built successfully');
end;

procedure BuildScriptLoader;
var
  Output: string;
begin
  WriteLn('');
  WriteLn('Building GocciaScriptLoader...');
  if not RunCommand('fpc', FPCArgs('source/app/GocciaScriptLoader.dpr'), Output) then
  begin
    WriteLn(Output);
    WriteLn('GocciaScriptLoader build failed');
    Halt(1);
  end;
  WriteLn(Output);
  WriteLn('GocciaScriptLoader built successfully');
  WriteLn('');
end;

procedure BuildTests;
var
  AllUnitFiles: TStringList;
  TestFiles: TStringList;
  Output: string;
  K: Integer;
begin
  WriteLn('Building Tests...');
  AllUnitFiles := TStringList.Create;
  TestFiles := TStringList.Create;

  AllUnitFiles.AddStrings(FindAllFiles('source/units', '.pas'));
  AllUnitFiles.AddStrings(FindAllFiles('source/shared', '.pas'));

  for K := 0 to AllUnitFiles.Count - 1 do
  begin
    if Pos('.Test.pas', AllUnitFiles[K]) > 0 then
      TestFiles.Add(AllUnitFiles[K]);
  end;

  for K := 0 to TestFiles.Count - 1 do
  begin
    if not RunCommand('fpc', FPCArgs(TestFiles[K]), Output) then
    begin
      WriteLn(Output);
      WriteLn('Test build failed: ', TestFiles[K]);
      Halt(1);
    end;
    WriteLn(Output);
  end;

  WriteLn('Tests built successfully');
end;

procedure BuildTestRunner;
var
  Output: string;
begin
  WriteLn('Building GocciaTestRunner...');
  if not RunCommand('fpc', FPCArgs('source/app/GocciaTestRunner.dpr'), Output) then
  begin
    WriteLn(Output);
    WriteLn('GocciaTestRunner build failed');
    Halt(1);
  end;
  WriteLn(Output);
  WriteLn('GocciaTestRunner built successfully');
end;

procedure BuildBenchmarkRunner;
var
  Output: string;
begin
  WriteLn('Building GocciaBenchmarkRunner...');
  if not RunCommand('fpc', FPCArgs('source/app/GocciaBenchmarkRunner.dpr'), Output) then
  begin
    WriteLn(Output);
    WriteLn('GocciaBenchmarkRunner build failed');
    Halt(1);
  end;
  WriteLn(Output);
  WriteLn('GocciaBenchmarkRunner built successfully');
end;

procedure BuildGocciaBundler;
var
  Output: string;
begin
  WriteLn('Building GocciaBundler...');
  if not RunCommand('fpc', FPCArgs('source/app/GocciaBundler.dpr'), Output) then
  begin
    WriteLn(Output);
    WriteLn('GocciaBundler build failed');
    Halt(1);
  end;
  WriteLn(Output);
  WriteLn('GocciaBundler built successfully');
end;

procedure Clean;
var
  Files: TStringList;
  K: Integer;
begin
  WriteLn('Cleaning build artifacts...');
  if not DirectoryExists('build/compiled') then
  begin
    WriteLn('Nothing to clean');
    Exit;
  end;

  Files := TStringList.Create;
  try
    Files.AddStrings(FindAllFiles('build/compiled', '.ppu'));
    Files.AddStrings(FindAllFiles('build/compiled', '.o'));
    Files.AddStrings(FindAllFiles('build/compiled', '.res'));

    for K := 0 to Files.Count - 1 do
      DeleteFile(Files[K]);

    WriteLn('Removed ', Files.Count, ' file(s)');
  finally
    Files.Free;
  end;
end;

procedure Build(const ATrigger: string);
begin
  if ATrigger = 'clean' then
    Clean
  else if ATrigger = 'repl' then
    BuildREPL
  else if ATrigger = 'loader' then
    BuildScriptLoader
  else if ATrigger = 'tests' then
    BuildTests
  else if ATrigger = 'testrunner' then
    BuildTestRunner
  else if ATrigger = 'benchmarkrunner' then
    BuildBenchmarkRunner
  else if ATrigger = 'bundler' then
    BuildGocciaBundler;
end;

begin
  if not DirectoryExists('build') then
    CreateDir('build');
  if not DirectoryExists('build/compiled') then
    CreateDir('build/compiled');

  BuildTriggers := TStringList.Create;

  for I := 1 to ParamCount do
  begin
    if ParamStr(I) = '--dev' then
      BuildMode := bmDev
    else if ParamStr(I) = '--prod' then
      BuildMode := bmProd
    else
      BuildTriggers.Add(LowerCase(ParamStr(I)));
  end;

  if BuildMode = bmProd then
    WriteLn('Build mode: production')
  else
    WriteLn('Build mode: development');

  WriteLn('');
  GVersion := ComputeVersion;
  GCommit := ComputeCommit;
  GBuildDate := ComputeBuildDate;
  GenerateVersionInclude(GVersion, GCommit, GBuildDate);
  PrintVersion(GVersion, GCommit, GBuildDate);
  PrintSourceStats;

  if BuildTriggers.Count = 0 then
  begin
    BuildTriggers.Add('clean');
    BuildTriggers.Add('tests');
    BuildTriggers.Add('loader');
    BuildTriggers.Add('testrunner');
    BuildTriggers.Add('benchmarkrunner');
    BuildTriggers.Add('bundler');
    BuildTriggers.Add('repl');
  end;

  for I := 0 to BuildTriggers.Count - 1 do
  begin
    Build(BuildTriggers[I]);
  end;

  BuildTriggers.Free;
end.
