/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/sysinit.o
/tmp/regexprtest.iU2h3Q.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/system.o
/var/folders/b1/k3rcgxx15vvcks4g79lcn6zh0000gn/T/tmp.cH8fApTB1V/fpc-3.2.2/packages/regexpr/src/regexpr.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/objpas.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/math.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/classes.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/sysutils.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/unix.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/errors.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/sysconst.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/unixtype.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/baseunix.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/sysctl.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/unixutil.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/initc.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/ctypes.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/types.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/typinfo.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/rtlconsts.o
