unit NumericText;

{$I Shared.inc}

interface

uses
  SysUtils;

function CreateInvariantFormatSettings: TFormatSettings;

// Uses each compiler's native RTL name for parsing an unsigned 64-bit value.
function TryTextToUInt64(const AText: string; out AValue: UInt64): Boolean;

// Converts a grammar-valid decimal numeral to the nearest binary64 value using
// round-to-nearest, ties-to-even. Invalid decimal text returns NaN. Callers
// with a narrower grammar (source literals, JSON, TOML) validate that grammar
// before delegating the decimal value conversion here.
function DecimalTextToNumber(const AText: string): Double;

// ES2026 Number::toString for radix 10. The result is the shortest decimal
// representation that round-trips to AValue, laid out using ECMAScript's
// fixed/scientific notation thresholds.
function NumberToString(const AValue: Double): string;

// Converts a String to a Number following the ECMA-262 StringToNumber
// abstract operation and the StringNumericLiteral grammar. Returns a raw
// Double (NaN for any input that is not a StringNumericLiteral) and performs
// no value-object allocation, so runtime primitive coercion and compile-time
// constant folding can share a single implementation instead of each keeping
// its own partial parser.
function StringToNumber(const AText: string): Double;

implementation

uses
  Math,

  BigInteger,
  NumberBits,
  TextSemantics;

const
  INFINITY_TEXT = 'Infinity';
  DECIMAL_EXPONENT_CLAMP = 1000000;
  DOUBLE_EXPONENT_BIAS = 1023;
  DOUBLE_EXPONENT_BITS = 11;
  DOUBLE_MANTISSA_BITS = 52;
  DOUBLE_MAXIMUM_EXPONENT = 1023;
  DOUBLE_MINIMUM_NORMAL_EXPONENT = -1022;
  DOUBLE_SUBNORMAL_SHIFT = 1074;
  RYU_DOUBLE_POWER_OF_FIVE_BIT_COUNT = 125;
  RYU_POWER_OF_FIVE_TABLE_SIZE = 26;

type
  TRyuDecimal = record
    Mantissa: UInt64;
    Exponent: Integer;
  end;

  TUInt128Parts = record
    Low: UInt64;
    High: UInt64;
  end;

const
  // Copyright 2018 Ulf Adams. This is a direct Pascal port of the binary64
  // shortest-conversion core from Ryu commit
  // 4c0618b0e44f7ef027ebae05d2cc7812048f7c8f, used under the Boost Software
  // License 1.0:
  //
  // Permission is hereby granted, free of charge, to any person or organization
  // obtaining a copy of the software and accompanying documentation covered by
  // this license (the "Software") to use, reproduce, display, distribute,
  // execute, and transmit the Software, and to prepare derivative works of the
  // Software, and to permit third-parties to whom the Software is furnished to
  // do so, all subject to the following:
  //
  // The copyright notices in the Software and this entire statement, including
  // the above license grant, this restriction and the following disclaimer,
  // must be included in all copies of the Software, in whole or in part, and all
  // derivative works of the Software, unless such copies or derivative works
  // are solely in the form of machine-executable object code generated by a
  // source language processor.
  //
  // THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  // IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  // FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  // SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  // FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  // ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  // DEALINGS IN THE SOFTWARE.
  RYU_INVERSE_POWER_OF_FIVE_SPLIT: array[0..14] of TUInt128Parts = (
    (Low: UInt64($0000000000000001); High: UInt64($2000000000000000)),
    (Low: UInt64($52A6C95FC0655034); High: UInt64($18C240C4AECB13BB)),
    (Low: UInt64($7CA8D50071DFC806); High: UInt64($1327FC58DA0F6FF5)),
    (Low: UInt64($6520247D3556476E); High: UInt64($1DA48CE468E7C702)),
    (Low: UInt64($6139CDD76802E6E9); High: UInt64($16EF5B40C2FC7779)),
    (Low: UInt64($F951A7FF43DE8C79); High: UInt64($11BEBDF578B2F391)),
    (Low: UInt64($7BE8BEE8D6E957E8); High: UInt64($1B758D848FAC54B0)),
    (Low: UInt64($8BD3F9E999A423EA); High: UInt64($153EDA614071A3B7)),
    (Low: UInt64($0848F973CB3EE3CE); High: UInt64($10701BD527B4978C)),
    (Low: UInt64($153285EBB9EFBFA2); High: UInt64($196FBB9BB44DB44D)),
    (Low: UInt64($ADEEE7F86C07B696); High: UInt64($13AE3591F5B4D936)),
    (Low: UInt64($4D686A4EAF182222); High: UInt64($1E74404F3DAADA91)),
    (Low: UInt64($98C0A106E09EBD9F); High: UInt64($17900EA4FDA7C257)),
    (Low: UInt64($8F20E37371497D0E); High: UInt64($123B140576D820B2)),
    (Low: UInt64($B043138134743D85); High: UInt64($1C35F4275F7A29AD))
  );

  RYU_INVERSE_POWER_OF_FIVE_OFFSETS: array[0..21] of UInt32 = (
    UInt32($54544554), UInt32($04055545), UInt32($10041000), UInt32($00400414),
    UInt32($40010000), UInt32($41155555), UInt32($00000454), UInt32($00010044),
    UInt32($40000000), UInt32($44000041), UInt32($50454450), UInt32($55550054),
    UInt32($51655554), UInt32($40004000), UInt32($01000001), UInt32($00010500),
    UInt32($51515411), UInt32($05555554), UInt32($50411500), UInt32($40040000),
    UInt32($05040110), UInt32($00000000)
  );

  RYU_POWER_OF_FIVE_SPLIT: array[0..12] of TUInt128Parts = (
    (Low: UInt64($0000000000000000); High: UInt64($1000000000000000)),
    (Low: UInt64($0000000000000000); High: UInt64($14ADF4B7320334B9)),
    (Low: UInt64($0E549208B31ADB10); High: UInt64($1ABA4714957D300D)),
    (Low: UInt64($6DC6AD264D8F0866); High: UInt64($1145B7E285BF98F5)),
    (Low: UInt64($EB1DBD923D8596CA); High: UInt64($1652EFDC6018A1FC)),
    (Low: UInt64($B4C1B80B22AE923C); High: UInt64($1CDA62055B2D9D83)),
    (Low: UInt64($5BB28B4E8F7E4C30); High: UInt64($12A5568B9F52F416)),
    (Low: UInt64($F08AED437682D4FB); High: UInt64($1819651531F9E78F)),
    (Low: UInt64($B4EE134AD99BF150); High: UInt64($1F25C186A6F04C28)),
    (Low: UInt64($16499ECB70C25F03); High: UInt64($1420EB449C8842E6)),
    (Low: UInt64($85A56EAD360865B0); High: UInt64($1A03FDE214CAF085)),
    (Low: UInt64($093DB1D57999890B); High: UInt64($10CFEB353A97DAD8)),
    (Low: UInt64($CF38BB735E3F36AC); High: UInt64($15BAAF44FA52673E))
  );

  RYU_POWER_OF_FIVE_OFFSETS: array[0..20] of UInt32 = (
    UInt32($00000000), UInt32($00000000), UInt32($00000000), UInt32($00000000),
    UInt32($40000000), UInt32($59695995), UInt32($55545555), UInt32($56555515),
    UInt32($41150504), UInt32($40555410), UInt32($44555145), UInt32($44504540),
    UInt32($45555550), UInt32($40004000), UInt32($96440440), UInt32($55565565),
    UInt32($54454045), UInt32($40154151), UInt32($55559155), UInt32($51405555),
    UInt32($00000105)
  );

  RYU_SMALL_POWER_OF_FIVE: array[0..RYU_POWER_OF_FIVE_TABLE_SIZE - 1] of UInt64 = (
    UInt64($0000000000000001), UInt64($0000000000000005),
    UInt64($0000000000000019), UInt64($000000000000007D),
    UInt64($0000000000000271), UInt64($0000000000000C35),
    UInt64($0000000000003D09), UInt64($000000000001312D),
    UInt64($000000000005F5E1), UInt64($00000000001DCD65),
    UInt64($00000000009502F9), UInt64($0000000002E90EDD),
    UInt64($000000000E8D4A51), UInt64($0000000048C27395),
    UInt64($000000016BCC41E9), UInt64($000000071AFD498D),
    UInt64($0000002386F26FC1), UInt64($000000B1A2BC2EC5),
    UInt64($000003782DACE9D9), UInt64($00001158E460913D),
    UInt64($000056BC75E2D631), UInt64($0001B1AE4D6E2EF5),
    UInt64($000878678326EAC9), UInt64($002A5A058FC295ED),
    UInt64($00D3C21BCECCEDA1), UInt64($0422CA8B0A00A425)
  );

function CreateInvariantFormatSettings: TFormatSettings;
begin
  {$IFDEF FPC}
  Result := DefaultFormatSettings;
  {$ELSE}
  Result := TFormatSettings.Invariant;
  {$ENDIF}
  Result.DecimalSeparator := '.';
end;

function TryTextToUInt64(const AText: string; out AValue: UInt64): Boolean;
begin
  {$IFDEF FPC}
  Result := TryStrToQWord(AText, AValue);
  {$ELSE}
  Result := TryStrToUInt64(AText, AValue);
  {$ENDIF}
end;

{$Q-}{$R-}

function RyuDecimalLength(const AValue: UInt64): Integer;
begin
  if AValue >= UInt64(10000000000000000) then Exit(17);
  if AValue >= UInt64(1000000000000000) then Exit(16);
  if AValue >= UInt64(100000000000000) then Exit(15);
  if AValue >= UInt64(10000000000000) then Exit(14);
  if AValue >= UInt64(1000000000000) then Exit(13);
  if AValue >= UInt64(100000000000) then Exit(12);
  if AValue >= UInt64(10000000000) then Exit(11);
  if AValue >= UInt64(1000000000) then Exit(10);
  if AValue >= UInt64(100000000) then Exit(9);
  if AValue >= UInt64(10000000) then Exit(8);
  if AValue >= UInt64(1000000) then Exit(7);
  if AValue >= UInt64(100000) then Exit(6);
  if AValue >= UInt64(10000) then Exit(5);
  if AValue >= UInt64(1000) then Exit(4);
  if AValue >= UInt64(100) then Exit(3);
  if AValue >= UInt64(10) then Exit(2);
  Result := 1;
end;

function RyuPowerOfFiveBits(const AExponent: Integer): Integer;
{$IFDEF FPC}inline;{$ENDIF}
begin
  Result := (UInt32(AExponent) * UInt32(1217359) shr 19) + 1;
end;

function RyuLog10PowerOfTwo(const AExponent: Integer): UInt32;
{$IFDEF FPC}inline;{$ENDIF}
begin
  Result := UInt32(AExponent) * UInt32(78913) shr 18;
end;

function RyuLog10PowerOfFive(const AExponent: Integer): UInt32;
{$IFDEF FPC}inline;{$ENDIF}
begin
  Result := UInt32(AExponent) * UInt32(732923) shr 20;
end;

function RyuMultiply128(const ALeft, ARight: UInt64;
  out AHigh: UInt64): UInt64;
var
  LeftLow, LeftHigh, RightLow, RightHigh: UInt32;
  ProductLowLow, ProductLowHigh, ProductHighLow, ProductHighHigh: UInt64;
  ProductLowLowLow, ProductLowLowHigh: UInt32;
  MiddleLow, MiddleHigh: UInt64;
  MiddleLowLow, MiddleLowHigh, MiddleHighLow, MiddleHighHigh: UInt32;
begin
  LeftLow := UInt32(ALeft);
  LeftHigh := UInt32(ALeft shr 32);
  RightLow := UInt32(ARight);
  RightHigh := UInt32(ARight shr 32);

  ProductLowLow := UInt64(LeftLow) * RightLow;
  ProductLowHigh := UInt64(LeftLow) * RightHigh;
  ProductHighLow := UInt64(LeftHigh) * RightLow;
  ProductHighHigh := UInt64(LeftHigh) * RightHigh;

  ProductLowLowLow := UInt32(ProductLowLow);
  ProductLowLowHigh := UInt32(ProductLowLow shr 32);

  MiddleLow := ProductHighLow + ProductLowLowHigh;
  MiddleLowLow := UInt32(MiddleLow);
  MiddleLowHigh := UInt32(MiddleLow shr 32);

  MiddleHigh := ProductLowHigh + MiddleLowLow;
  MiddleHighLow := UInt32(MiddleHigh);
  MiddleHighHigh := UInt32(MiddleHigh shr 32);

  AHigh := ProductHighHigh + MiddleLowHigh + MiddleHighHigh;
  Result := UInt64(MiddleHighLow) shl 32 or ProductLowLowLow;
end;

function RyuShiftRight128(const ALow, AHigh: UInt64;
  const ADistance: Integer): UInt64;
  {$IFDEF FPC}inline;{$ENDIF}
begin
  Result := AHigh shl (64 - ADistance) or ALow shr ADistance;
end;

function RyuMultiplyShift(const AMantissa: UInt64;
  const AMultiplier: TUInt128Parts; const ADistance: Integer): UInt64;
var
  HighProduct, LowProduct, HighCarry, Sum: UInt64;
begin
  LowProduct := RyuMultiply128(AMantissa, AMultiplier.High, HighProduct);
  RyuMultiply128(AMantissa, AMultiplier.Low, HighCarry);
  Sum := HighCarry + LowProduct;
  if Sum < HighCarry then
    Inc(HighProduct);
  Result := RyuShiftRight128(Sum, HighProduct, ADistance - 64);
end;

function RyuMultiplyShiftBounds(const AMantissa: UInt64;
  const AMultiplier: TUInt128Parts; const ADistance: Integer;
  out AUpper, ALower: UInt64; const ALowerShift: UInt32): UInt64;
begin
  AUpper := RyuMultiplyShift(4 * AMantissa + 2, AMultiplier, ADistance);
  ALower := RyuMultiplyShift(4 * AMantissa - 1 - ALowerShift,
    AMultiplier, ADistance);
  Result := RyuMultiplyShift(4 * AMantissa, AMultiplier, ADistance);
end;

procedure RyuComputePowerOfFive(const AExponent: UInt32;
  out AResult: TUInt128Parts);
var
  Base, BaseExponent, Offset, Delta: UInt32;
  Multiplier: TUInt128Parts;
  SmallPower, LowProduct, LowBaseProduct, HighProduct, CarryProduct,
  Sum: UInt64;
  Adjustment: UInt32;
begin
  Base := AExponent div RYU_POWER_OF_FIVE_TABLE_SIZE;
  BaseExponent := Base * RYU_POWER_OF_FIVE_TABLE_SIZE;
  Offset := AExponent - BaseExponent;
  Multiplier := RYU_POWER_OF_FIVE_SPLIT[Base];
  if Offset = 0 then
  begin
    AResult := Multiplier;
    Exit;
  end;

  SmallPower := RYU_SMALL_POWER_OF_FIVE[Offset];
  LowProduct := RyuMultiply128(SmallPower, Multiplier.High, HighProduct);
  LowBaseProduct := RyuMultiply128(SmallPower, Multiplier.Low, CarryProduct);
  Sum := CarryProduct + LowProduct;
  if Sum < CarryProduct then
    Inc(HighProduct);

  Delta := RyuPowerOfFiveBits(AExponent) - RyuPowerOfFiveBits(BaseExponent);
  Adjustment := (RYU_POWER_OF_FIVE_OFFSETS[AExponent div 16] shr
    ((AExponent mod 16) shl 1)) and 3;
  AResult.Low := RyuShiftRight128(LowBaseProduct, Sum, Delta) + Adjustment;
  AResult.High := RyuShiftRight128(Sum, HighProduct, Delta);
end;

procedure RyuComputeInversePowerOfFive(const AExponent: UInt32;
  out AResult: TUInt128Parts);
var
  Base, BaseExponent, Offset, Delta: UInt32;
  Multiplier: TUInt128Parts;
  SmallPower, LowProduct, LowBaseProduct, HighProduct, CarryProduct,
  Sum: UInt64;
  Adjustment: UInt32;
begin
  Base := (AExponent + RYU_POWER_OF_FIVE_TABLE_SIZE - 1) div
    RYU_POWER_OF_FIVE_TABLE_SIZE;
  BaseExponent := Base * RYU_POWER_OF_FIVE_TABLE_SIZE;
  Offset := BaseExponent - AExponent;
  Multiplier := RYU_INVERSE_POWER_OF_FIVE_SPLIT[Base];
  if Offset = 0 then
  begin
    AResult := Multiplier;
    Exit;
  end;

  SmallPower := RYU_SMALL_POWER_OF_FIVE[Offset];
  LowProduct := RyuMultiply128(SmallPower, Multiplier.High, HighProduct);
  LowBaseProduct := RyuMultiply128(SmallPower, Multiplier.Low - 1,
    CarryProduct);
  Sum := CarryProduct + LowProduct;
  if Sum < CarryProduct then
    Inc(HighProduct);

  Delta := RyuPowerOfFiveBits(BaseExponent) - RyuPowerOfFiveBits(AExponent);
  Adjustment := (RYU_INVERSE_POWER_OF_FIVE_OFFSETS[AExponent div 16] shr
    ((AExponent mod 16) shl 1)) and 3;
  AResult.Low := RyuShiftRight128(LowBaseProduct, Sum, Delta) + 1 +
    Adjustment;
  AResult.High := RyuShiftRight128(Sum, HighProduct, Delta);
end;

function RyuPowerOfFiveFactor(AValue: UInt64): UInt32;
const
  INVERSE_FIVE: UInt64 = UInt64($CCCCCCCCCCCCCCCD);
  MAXIMUM_DIVISIBLE_BY_FIVE: UInt64 = UInt64($3333333333333333);
begin
  Result := 0;
  repeat
    AValue := AValue * INVERSE_FIVE;
    if AValue > MAXIMUM_DIVISIBLE_BY_FIVE then
      Exit;
    Inc(Result);
  until False;
end;

function RyuIsMultipleOfPowerOfFive(const AValue: UInt64;
  const APower: UInt32): Boolean;
  {$IFDEF FPC}inline;{$ENDIF}
begin
  Result := RyuPowerOfFiveFactor(AValue) >= APower;
end;

function RyuIsMultipleOfPowerOfTwo(const AValue: UInt64;
  const APower: UInt32): Boolean;
  {$IFDEF FPC}inline;{$ENDIF}
begin
  Result := (AValue and ((UInt64(1) shl APower) - 1)) = 0;
end;

function RyuToDecimal(const AIEEEEMantissa: UInt64;
  const AIEEEExponent: UInt32): TRyuDecimal;
var
  BinaryExponent, DecimalExponent, Shift, PowerBits: Integer;
  BinaryMantissa, MovedMantissa: UInt64;
  AcceptBounds, LowerIsTrailingZeros, ValueIsTrailingZeros: Boolean;
  LowerShift, Power, MovedModFive: UInt32;
  Multiplier: TUInt128Parts;
  Value, Upper, Lower: UInt64;
  Removed, LastRemovedDigit: Integer;
  UpperDivisor, LowerDivisor, ValueDivisor: UInt64;
  LowerRemainder, ValueRemainder: UInt32;
  RoundUp: Boolean;
begin
  if AIEEEExponent = 0 then
  begin
    BinaryExponent := 1 - DOUBLE_EXPONENT_BIAS - DOUBLE_MANTISSA_BITS - 2;
    BinaryMantissa := AIEEEEMantissa;
  end
  else
  begin
    BinaryExponent := Integer(AIEEEExponent) - DOUBLE_EXPONENT_BIAS -
      DOUBLE_MANTISSA_BITS - 2;
    BinaryMantissa := UInt64(1) shl DOUBLE_MANTISSA_BITS or AIEEEEMantissa;
  end;

  AcceptBounds := (BinaryMantissa and 1) = 0;
  MovedMantissa := 4 * BinaryMantissa;
  if (AIEEEEMantissa <> 0) or (AIEEEExponent <= 1) then
    LowerShift := 1
  else
    LowerShift := 0;

  LowerIsTrailingZeros := False;
  ValueIsTrailingZeros := False;
  if BinaryExponent >= 0 then
  begin
    Power := RyuLog10PowerOfTwo(BinaryExponent);
    if BinaryExponent > 3 then
      Dec(Power);
    DecimalExponent := Integer(Power);
    PowerBits := RYU_DOUBLE_POWER_OF_FIVE_BIT_COUNT +
      RyuPowerOfFiveBits(Power) - 1;
    Shift := -BinaryExponent + Integer(Power) + PowerBits;
    RyuComputeInversePowerOfFive(Power, Multiplier);
    Value := RyuMultiplyShiftBounds(BinaryMantissa, Multiplier, Shift,
      Upper, Lower, LowerShift);

    if Power <= 21 then
    begin
      MovedModFive := UInt32(MovedMantissa) -
        5 * UInt32(MovedMantissa div 5);
      if MovedModFive = 0 then
        ValueIsTrailingZeros := RyuIsMultipleOfPowerOfFive(
          MovedMantissa, Power)
      else if AcceptBounds then
        LowerIsTrailingZeros := RyuIsMultipleOfPowerOfFive(
          MovedMantissa - 1 - LowerShift, Power)
      else if RyuIsMultipleOfPowerOfFive(MovedMantissa + 2, Power) then
        Dec(Upper);
    end;
  end
  else
  begin
    Power := RyuLog10PowerOfFive(-BinaryExponent);
    if -BinaryExponent > 1 then
      Dec(Power);
    DecimalExponent := Integer(Power) + BinaryExponent;
    Shift := -BinaryExponent - Integer(Power);
    PowerBits := RyuPowerOfFiveBits(Shift) -
      RYU_DOUBLE_POWER_OF_FIVE_BIT_COUNT;
    Shift := Integer(Power) - PowerBits;
    RyuComputePowerOfFive(UInt32(-BinaryExponent - Integer(Power)),
      Multiplier);
    Value := RyuMultiplyShiftBounds(BinaryMantissa, Multiplier, Shift,
      Upper, Lower, LowerShift);

    if Power <= 1 then
    begin
      ValueIsTrailingZeros := True;
      if AcceptBounds then
        LowerIsTrailingZeros := LowerShift = 1
      else
        Dec(Upper);
    end
    else if Power < 63 then
      ValueIsTrailingZeros := RyuIsMultipleOfPowerOfTwo(MovedMantissa,
        Power);
  end;

  Removed := 0;
  LastRemovedDigit := 0;
  if LowerIsTrailingZeros or ValueIsTrailingZeros then
  begin
    while True do
    begin
      UpperDivisor := Upper div 10;
      LowerDivisor := Lower div 10;
      if UpperDivisor <= LowerDivisor then
        Break;
      LowerRemainder := UInt32(Lower) - 10 * UInt32(LowerDivisor);
      ValueDivisor := Value div 10;
      ValueRemainder := UInt32(Value) - 10 * UInt32(ValueDivisor);
      LowerIsTrailingZeros := LowerIsTrailingZeros and
        (LowerRemainder = 0);
      ValueIsTrailingZeros := ValueIsTrailingZeros and
        (LastRemovedDigit = 0);
      LastRemovedDigit := ValueRemainder;
      Value := ValueDivisor;
      Upper := UpperDivisor;
      Lower := LowerDivisor;
      Inc(Removed);
    end;

    if LowerIsTrailingZeros then
    begin
      while True do
      begin
        LowerDivisor := Lower div 10;
        LowerRemainder := UInt32(Lower) - 10 * UInt32(LowerDivisor);
        if LowerRemainder <> 0 then
          Break;
        UpperDivisor := Upper div 10;
        ValueDivisor := Value div 10;
        ValueRemainder := UInt32(Value) - 10 * UInt32(ValueDivisor);
        ValueIsTrailingZeros := ValueIsTrailingZeros and
          (LastRemovedDigit = 0);
        LastRemovedDigit := ValueRemainder;
        Value := ValueDivisor;
        Upper := UpperDivisor;
        Lower := LowerDivisor;
        Inc(Removed);
      end;
    end;

    if ValueIsTrailingZeros and (LastRemovedDigit = 5) and
       ((Value and 1) = 0) then
      LastRemovedDigit := 4;
    Result.Mantissa := Value;
    if ((Value = Lower) and
        ((not AcceptBounds) or (not LowerIsTrailingZeros))) or
       (LastRemovedDigit >= 5) then
      Inc(Result.Mantissa);
  end
  else
  begin
    RoundUp := False;
    UpperDivisor := Upper div 100;
    LowerDivisor := Lower div 100;
    if UpperDivisor > LowerDivisor then
    begin
      ValueDivisor := Value div 100;
      ValueRemainder := UInt32(Value) - 100 * UInt32(ValueDivisor);
      RoundUp := ValueRemainder >= 50;
      Value := ValueDivisor;
      Upper := UpperDivisor;
      Lower := LowerDivisor;
      Inc(Removed, 2);
    end;

    while True do
    begin
      UpperDivisor := Upper div 10;
      LowerDivisor := Lower div 10;
      if UpperDivisor <= LowerDivisor then
        Break;
      ValueDivisor := Value div 10;
      ValueRemainder := UInt32(Value) - 10 * UInt32(ValueDivisor);
      RoundUp := ValueRemainder >= 5;
      Value := ValueDivisor;
      Upper := UpperDivisor;
      Lower := LowerDivisor;
      Inc(Removed);
    end;

    Result.Mantissa := Value;
    if (Value = Lower) or RoundUp then
      Inc(Result.Mantissa);
  end;

  Result.Exponent := DecimalExponent + Removed;
end;

function RyuSmallInteger(const AIEEEEMantissa: UInt64;
  const AIEEEExponent: UInt32; out ADecimal: TRyuDecimal): Boolean;
var
  BinaryMantissa, Mask, Fraction: UInt64;
  BinaryExponent: Integer;
begin
  BinaryMantissa := UInt64(1) shl DOUBLE_MANTISSA_BITS or AIEEEEMantissa;
  BinaryExponent := Integer(AIEEEExponent) - DOUBLE_EXPONENT_BIAS -
    DOUBLE_MANTISSA_BITS;
  if (BinaryExponent > 0) or (BinaryExponent < -DOUBLE_MANTISSA_BITS) then
    Exit(False);

  Mask := (UInt64(1) shl -BinaryExponent) - 1;
  Fraction := BinaryMantissa and Mask;
  if Fraction <> 0 then
    Exit(False);

  ADecimal.Mantissa := BinaryMantissa shr -BinaryExponent;
  ADecimal.Exponent := 0;
  Result := True;
end;

function RyuShortestDecimal(const AValue: Double): TRyuDecimal;
var
  Bits, MantissaMask: UInt64;
  IEEEExponent: UInt32;
begin
  Bits := DoubleToBits(AValue);
  MantissaMask := (UInt64(1) shl DOUBLE_MANTISSA_BITS) - 1;
  Result.Mantissa := Bits and MantissaMask;
  IEEEExponent := UInt32((Bits shr DOUBLE_MANTISSA_BITS) and
    ((UInt64(1) shl DOUBLE_EXPONENT_BITS) - 1));

  if RyuSmallInteger(Result.Mantissa, IEEEExponent, Result) then
  begin
    while (Result.Mantissa mod 10) = 0 do
    begin
      Result.Mantissa := Result.Mantissa div 10;
      Inc(Result.Exponent);
    end;
  end
  else
    Result := RyuToDecimal(Bits and MantissaMask, IEEEExponent);
end;

{$IFDEF PRODUCTION}{$Q-}{$R-}{$ELSE}{$Q+}{$R+}{$ENDIF}

procedure FormatECMAScriptDecimal(const AMantissa: string;
  const ADecimalExponent: Integer; const ANegative: Boolean;
  out AResult: string);
var
  DigitCount, DecimalPoint, ScientificExponent: Integer;
begin
  DigitCount := Length(AMantissa);
  DecimalPoint := DigitCount + ADecimalExponent;

  if (DigitCount <= DecimalPoint) and (DecimalPoint <= 21) then
    AResult := AMantissa + StringOfChar('0', DecimalPoint - DigitCount)
  else if (0 < DecimalPoint) and (DecimalPoint <= 21) then
    AResult := Copy(AMantissa, 1, DecimalPoint) + '.' +
      Copy(AMantissa, DecimalPoint + 1, DigitCount - DecimalPoint)
  else if (DecimalPoint > -6) and (DecimalPoint <= 0) then
    AResult := '0.' + StringOfChar('0', -DecimalPoint) + AMantissa
  else
  begin
    ScientificExponent := DecimalPoint - 1;
    if DigitCount = 1 then
      AResult := AMantissa
    else
      AResult := AMantissa[1] + '.' + Copy(AMantissa, 2,
        DigitCount - 1);
    if ScientificExponent >= 0 then
      AResult := AResult + 'e+' + IntToStr(ScientificExponent)
    else
      AResult := AResult + 'e-' + IntToStr(-ScientificExponent);
  end;

  if ANegative then
    AResult := '-' + AResult;
end;

// ES2026 §6.1.6.1.20 Number::toString ( x, radix ) for radix 10.
function NumberToString(const AValue: Double): string;
var
  AbsoluteValue: Double;
  Decimal: TRyuDecimal;
  Negative: Boolean;
begin
  if IsNan(AValue) then
    Exit('NaN');
  if IsInfinite(AValue) then
  begin
    if AValue < 0 then
      Exit('-Infinity');
    Exit('Infinity');
  end;
  if AValue = 0 then
    Exit('0');

  Negative := AValue < 0;
  if Negative then
    AbsoluteValue := -AValue
  else
    AbsoluteValue := AValue;
  Decimal := RyuShortestDecimal(AbsoluteValue);
  FormatECMAScriptDecimal(IntToStr(Int64(Decimal.Mantissa)),
    Decimal.Exponent, Negative, Result);
end;

function SignedZero(const ANegative: Boolean): Double;
{$IFDEF FPC}inline;{$ENDIF}
begin
  if ANegative then
    Result := BitsToDouble(UInt64(1) shl 63)
  else
    Result := 0.0;
end;

function SignedInfinity(const ANegative: Boolean): Double;
{$IFDEF FPC}inline;{$ENDIF}
begin
  if ANegative then
    Result := BitsToDouble(UInt64($FFF0000000000000))
  else
    Result := BitsToDouble(UInt64($7FF0000000000000));
end;

function TryDecimalComponents(const AText: string; out ANegative: Boolean;
  out ADigits: string; out ADecimalExponent: Int64): Boolean;
var
  Index, FractionDigits, LeadingZeroIndex, TrailingZeroIndex: Integer;
  ExponentNegative, HasExponent: Boolean;
  ExponentValue: Int64;
  Character: Char;
begin
  Result := False;
  ANegative := False;
  ADigits := '';
  ADecimalExponent := 0;
  FractionDigits := 0;
  Index := 1;

  if Index <= Length(AText) then
  begin
    if AText[Index] = '-' then
    begin
      ANegative := True;
      Inc(Index);
    end
    else if AText[Index] = '+' then
      Inc(Index);
  end;

  while (Index <= Length(AText)) and (AText[Index] in ['0'..'9']) do
  begin
    ADigits := ADigits + AText[Index];
    Inc(Index);
  end;

  if (Index <= Length(AText)) and (AText[Index] = '.') then
  begin
    Inc(Index);
    while (Index <= Length(AText)) and (AText[Index] in ['0'..'9']) do
    begin
      ADigits := ADigits + AText[Index];
      Inc(FractionDigits);
      Inc(Index);
    end;
  end;

  if ADigits = '' then
    Exit;

  ExponentValue := 0;
  ExponentNegative := False;
  HasExponent := False;
  if (Index <= Length(AText)) and
     ((AText[Index] = 'e') or (AText[Index] = 'E')) then
  begin
    HasExponent := True;
    Inc(Index);
    if (Index <= Length(AText)) and
       ((AText[Index] = '+') or (AText[Index] = '-')) then
    begin
      ExponentNegative := AText[Index] = '-';
      Inc(Index);
    end;
    if (Index > Length(AText)) or not (AText[Index] in ['0'..'9']) then
      Exit;
    while (Index <= Length(AText)) and (AText[Index] in ['0'..'9']) do
    begin
      Character := AText[Index];
      if ExponentValue < DECIMAL_EXPONENT_CLAMP then
      begin
        ExponentValue := ExponentValue * 10 + Ord(Character) - Ord('0');
        if ExponentValue > DECIMAL_EXPONENT_CLAMP then
          ExponentValue := DECIMAL_EXPONENT_CLAMP;
      end;
      Inc(Index);
    end;
  end;

  if Index <= Length(AText) then
    Exit;
  if HasExponent and ExponentNegative then
    ExponentValue := -ExponentValue;
  ADecimalExponent := ExponentValue - FractionDigits;

  LeadingZeroIndex := 1;
  while (LeadingZeroIndex <= Length(ADigits)) and
        (ADigits[LeadingZeroIndex] = '0') do
    Inc(LeadingZeroIndex);
  if LeadingZeroIndex > Length(ADigits) then
  begin
    ADigits := '';
    Exit(True);
  end;
  if LeadingZeroIndex > 1 then
    Delete(ADigits, 1, LeadingZeroIndex - 1);

  TrailingZeroIndex := Length(ADigits);
  while (TrailingZeroIndex > 1) and
        (ADigits[TrailingZeroIndex] = '0') do
  begin
    Dec(TrailingZeroIndex);
    Inc(ADecimalExponent);
  end;
  SetLength(ADigits, TrailingZeroIndex);
  Result := True;
end;

function PowerOfFive(const AExponent: Integer): TBigInteger;
{$IFDEF FPC}inline;{$ENDIF}
begin
  Result := TBigInteger.FromInt64(5).Power(
    TBigInteger.FromInt64(AExponent));
end;

function CompareRationalToPowerOfTwo(const ANumerator,
  ADenominator: TBigInteger; const ABinaryScale,
  APower: Integer): Integer;
var
  Shift: Integer;
begin
  Shift := ABinaryScale - APower;
  if Shift >= 0 then
    Result := ANumerator.ShiftLeft(Shift).Compare(ADenominator)
  else
    Result := ANumerator.Compare(ADenominator.ShiftLeft(-Shift));
end;

function RoundRationalToUInt64(const ANumerator,
  ADenominator: TBigInteger; const ABinaryShift: Integer): UInt64;
var
  ScaledNumerator, ScaledDenominator, Remainder,
  ShiftedDenominator: TBigInteger;
  DivisorShift, RemainderComparison: Integer;
begin
  if ABinaryShift >= 0 then
  begin
    ScaledNumerator := ANumerator.ShiftLeft(ABinaryShift);
    ScaledDenominator := ADenominator;
  end
  else
  begin
    ScaledNumerator := ANumerator;
    ScaledDenominator := ADenominator.ShiftLeft(-ABinaryShift);
  end;

  // The rounded binary64 significand has at most 54 bits. Compute that small
  // quotient by exact subtract-and-shift division instead of depending on the
  // general BigInteger Knuth divider for this semantic boundary.
  Result := 0;
  Remainder := ScaledNumerator;
  DivisorShift := Remainder.BitLength - ScaledDenominator.BitLength;
  while DivisorShift >= 0 do
  begin
    ShiftedDenominator := ScaledDenominator.ShiftLeft(DivisorShift);
    if Remainder.Compare(ShiftedDenominator) >= 0 then
    begin
      Remainder := Remainder.Subtract(ShiftedDenominator);
      Result := Result or (UInt64(1) shl DivisorShift);
    end;
    Dec(DivisorShift);
  end;

  RemainderComparison := Remainder.ShiftLeft(1).Compare(ScaledDenominator);
  if (RemainderComparison > 0) or
     ((RemainderComparison = 0) and ((Result and 1) <> 0)) then
    Inc(Result);
end;

function ExactDecimalToNumber(const ADigits: string;
  const ADecimalExponent: Integer; const ANegative: Boolean): Double;
var
  Numerator, Denominator, FivePower: TBigInteger;
  BinaryScale, BinaryExponent: Integer;
  Significand, Bits: UInt64;
begin
  Numerator := TBigInteger.FromDecimalString(ADigits);
  Denominator := TBigInteger.One;
  BinaryScale := ADecimalExponent;
  if ADecimalExponent >= 0 then
  begin
    FivePower := PowerOfFive(ADecimalExponent);
    Numerator := Numerator.Multiply(FivePower);
  end
  else
    Denominator := PowerOfFive(-ADecimalExponent);

  BinaryExponent := Numerator.BitLength - Denominator.BitLength +
    BinaryScale;
  if CompareRationalToPowerOfTwo(Numerator, Denominator, BinaryScale,
     BinaryExponent) < 0 then
    Dec(BinaryExponent);

  if BinaryExponent < DOUBLE_MINIMUM_NORMAL_EXPONENT then
  begin
    Significand := RoundRationalToUInt64(Numerator, Denominator,
      BinaryScale + DOUBLE_SUBNORMAL_SHIFT);
    if Significand = 0 then
      Exit(SignedZero(ANegative));
    Bits := Significand;
  end
  else
  begin
    Significand := RoundRationalToUInt64(Numerator, Denominator,
      BinaryScale - BinaryExponent + DOUBLE_MANTISSA_BITS);
    if Significand = (UInt64(1) shl (DOUBLE_MANTISSA_BITS + 1)) then
    begin
      Significand := Significand shr 1;
      Inc(BinaryExponent);
    end;
    if BinaryExponent > DOUBLE_MAXIMUM_EXPONENT then
      Exit(SignedInfinity(ANegative));
    Bits := UInt64(BinaryExponent + DOUBLE_EXPONENT_BIAS) shl
      DOUBLE_MANTISSA_BITS;
    Bits := Bits or (Significand -
      (UInt64(1) shl DOUBLE_MANTISSA_BITS));
  end;

  if ANegative then
    Bits := Bits or (UInt64(1) shl 63);
  Result := BitsToDouble(Bits);
end;

function HexDigitValue(const AChar: Char): Integer;
begin
  case AChar of
    '0'..'9': Result := Ord(AChar) - Ord('0');
    'a'..'f': Result := Ord(AChar) - Ord('a') + 10;
    'A'..'F': Result := Ord(AChar) - Ord('A') + 10;
  else
    Result := -1;
  end;
end;

// ES2026 §7.1.4.1 NonDecimalIntegerLiteral (BinaryIntegerLiteral,
// OctalIntegerLiteral, HexIntegerLiteral). These never carry a leading sign.
// Returns True when AText has a 0b / 0o / 0x prefix and therefore belongs to
// the non-decimal space; ANumber is then the parsed value, or NaN when the
// digits after the prefix are missing or invalid for the radix.
function TryNonDecimalIntegerToNumber(const AText: string;
  out ANumber: Double): Boolean;
var
  Radix: Integer;
  Index: Integer;
  DigitValue: Integer;
  IntegerValue: TBigInteger;
  Digits: string;
begin
  Result := False;
  if (Length(AText) < 2) or (AText[1] <> '0') then
    Exit;

  case AText[2] of
    'b', 'B': Radix := 2;
    'o', 'O': Radix := 8;
    'x', 'X': Radix := 16;
  else
    Exit;
  end;

  Result := True;

  if Length(AText) < 3 then
  begin
    ANumber := NaN;
    Exit;
  end;

  for Index := 3 to Length(AText) do
  begin
    DigitValue := HexDigitValue(AText[Index]);
    if (DigitValue < 0) or (DigitValue >= Radix) then
    begin
      ANumber := NaN;
      Exit;
    end;
  end;
  Digits := Copy(AText, 3, Length(AText) - 2);
  case Radix of
    2: IntegerValue := TBigInteger.FromBinaryString(Digits);
    8: IntegerValue := TBigInteger.FromOctalString(Digits);
  else
    IntegerValue := TBigInteger.FromHexString(Digits);
  end;
  ANumber := IntegerValue.ToDouble;
end;

// ES2026 §7.1.4.1.2 Runtime Semantics: StringNumericValue.
function DecimalTextToNumber(const AText: string): Double;
var
  Negative: Boolean;
  Digits: string;
  DecimalExponent, DecimalOrder: Int64;
begin
  if not TryDecimalComponents(AText, Negative, Digits,
     DecimalExponent) then
    Exit(NaN);
  if Digits = '' then
    Exit(SignedZero(Negative));

  DecimalOrder := Int64(Length(Digits)) + DecimalExponent - 1;
  if DecimalOrder > 308 then
    Exit(SignedInfinity(Negative));
  if DecimalOrder < -324 then
    Exit(SignedZero(Negative));

  Result := ExactDecimalToNumber(Digits, Integer(DecimalExponent), Negative);
end;

// ES2026 §7.1.4.1.1 StringToNumber ( str )
function StringToNumber(const AText: string): Double;
var
  Trimmed: string;
begin
  // StringNumericLiteral allows leading and trailing ECMAScript whitespace.
  Trimmed := TrimECMAScriptWhitespace(AText);

  // StringNumericLiteral ::: [empty] evaluates to +0.
  if Trimmed = '' then
    Exit(0.0);

  // StrDecimalLiteral ::: (+ | -)? Infinity
  if Trimmed = INFINITY_TEXT then
    Exit(Infinity);
  if Trimmed = '+' + INFINITY_TEXT then
    Exit(Infinity);
  if Trimmed = '-' + INFINITY_TEXT then
    Exit(NegInfinity);

  // NonDecimalIntegerLiteral ::: 0b... | 0o... | 0x...  (no sign permitted)
  if TryNonDecimalIntegerToNumber(Trimmed, Result) then
    Exit;

  // StrDecimalLiteral, or NaN when the text is not a StringNumericLiteral.
  Result := DecimalTextToNumber(Trimmed);
end;

end.
